### Statistical Rethinking - Chapter 3

Work through problems from the book below.

## Setup

Run this cell first to import required libraries.

In [2]:
import os
import arviz as az
import matplotlib.pyplot as plt
import jax.numpy as jnp
from jax import random

import numpyro  
import numpyro.distributions as dist
import numpyro.optim as optim
from numpyro.infer import SVI, Trace_ELBO
from numpyro.infer.autoguide import AutoLaplaceApproximation
from typing import List

az.style.use("arviz-darkgrid")
numpyro.set_platform("cpu")

print("✓ Environment ready!")
print(f"NumPyro version: {numpyro.__version__}")

/Users/annecarlson/bookbub/statistical-rethinking-practice/.venv/lib/python3.11/site-packages/arviz/__init__.py:50: FutureWarning: 
ArviZ is undergoing a major refactor to improve flexibility and extensibility while maintaining a user-friendly interface.
Some upcoming changes may be backward incompatible.
For details and migration guidance, visit: https://python.arviz.org/en/latest/user_guide/migration_guide.html
  warn(


✓ Environment ready!
NumPyro version: 0.21.0


## Work Area

Add cells below for your solutions. Use:
- `B` key (in command mode) to insert cell below
- `M` key to convert cell to markdown (for notes/explanations)
- `Y` key to convert cell to code
- `Shift+Enter` to run cell and move to next

In [3]:
p_grid = jnp.linspace(start=0, stop=1, num=1000)
prior = jnp.repeat(1, 1000)
likelihood = jnp.exp(dist.Binomial(total_count=9, probs=p_grid).log_prob(6))
posterior = likelihood * prior
posterior = posterior / jnp.sum(posterior)
samples = p_grid[dist.Categorical(posterior).sample(random.PRNGKey(100), (10000,))]

# 3E1

In [12]:
jnp.sum(samples < 0.2) / 10000

Array(0.001, dtype=float32)

# 3E2

In [13]:
jnp.sum(samples > 0.8) / 10000

Array(0.1231, dtype=float32)

# 3E3

In [ ]:
1-jnp.sum(samples > 0.8) / 10000-jnp.sum(samples < 0.2) / 10000

# 3E4

In [18]:
jnp.quantile(samples, 0.2)

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


Array(0.7607607, dtype=float32)

# 3E5

In [19]:
jnp.quantile(samples, 0.8)

Array(0.7607607, dtype=float32)

# 3E6

In [20]:
numpyro.diagnostics.hpdi(samples, prob=0.66)

array([0.5155155, 0.7917918], dtype=float32)

# 3E7

In [22]:
jnp.percentile(samples, q=jnp.array([16, 83]))

Array([0.4904905, 0.7749449], dtype=float32)

# 3M1

In [23]:
p_grid = jnp.linspace(start=0, stop=1, num=1000)
prior = jnp.repeat(1, 1000)
likelihood = jnp.exp(dist.Binomial(total_count=15, probs=p_grid).log_prob(8))
posterior = likelihood * prior
posterior = posterior / jnp.sum(posterior)

# 3M2

In [25]:
samples = p_grid[dist.Categorical(posterior).sample(random.PRNGKey(100), (10000,))]
numpyro.diagnostics.hpdi(samples, prob=0.9)

array([0.33333334, 0.7227227 ], dtype=float32)

# 3M3

In [33]:
w = dist.Binomial(total_count=15, probs=samples).sample(random.PRNGKey(0))
jnp.unique(w, return_counts=True)[1][8] / 10000

Array(0.1518, dtype=float32)

# HARD

In [34]:
birth1 = [
    1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
    0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
    1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
    0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
]
birth2 = [
    0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
    0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
    0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
]

## 1